baseURL = 'https://alienchow.github.io/'
languageCode = 'en-us'
title = 'Alienchow'
theme = 'anubis2'

[menu]
    [[menu.main]]
        name = "Home"
        weight = 1
        url = "/"
    [[menu.main]]
        name = "Categories"
        weight = 2
        url = "/categories/"
    [[menu.main]]
        name = "Tags"
        weight = 3
        url = "/tags/"
    [[menu.main]]
        name = "About"
        weight = 4
        url = "/about/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    [[params.social]]
        id = "github"
        name = "alienchow"

