baseURL = 'https://alienchow.github.io/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
title = 'Alienchow'
theme = 'techpro'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1
  [languages.zh]
    languageName = '中文'
    weight = 2
  [languages.de]
    languageName = 'Deutsch'
    weight = 3
  [languages.ja]
    languageName = '日本語'
    weight = 4
  [languages.es]
    languageName = 'Español'
    weight = 5

[menu]
    [[menu.main]]
        name = "Home"
        weight = 1
        url = "/"
    [[menu.main]]
        name = "Categories"
        weight = 2
        url = "/categories/"
    [[menu.main]]
        name = "Tags"
        weight = 3
        url = "/tags/"
    [[menu.main]]
        name = "About"
        weight = 4
        url = "/about/"

[taxonomies]
    tag = "tags"
    category = "categories"

[outputs]
    home = ["HTML", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"
  [markup.goldmark.renderer]
    unsafe = true



[params]
    darkMode = true
    [[params.social]]
        id = "github"
        name = "alienchow"
    [[params.social]]
        id = "linkedin"
        name = "lianyuanlin"
